services:
  retrieval-api:
    env_file:
      - path: retrieval-api/.env.retrieval-api.sample
        required: true
      - path: .env.provider.aws
        required: true
      - path: .env.demo
        required: true
    build: retrieval-api
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./retrieval-api/app:/workspace/app
    environment:
      APP_ENVIRONMENT: development
      CORS_ORIGINS: '["http://localhost:3000"]'
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  advisor-ui:
    env_file:
      - path: advisor-ui/.env.advisor-ui.sample
        required: true
      - path: .env.provider.vercel
        required: true
      - path: .env.demo
        required: true
    build:
      context: advisor-ui
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "24678:24678" # Nuxt HMR websocket
    depends_on:
      - retrieval-api
    volumes:
      - ./advisor-ui:/workspace
      - advisor_ui_node_modules:/workspace/node_modules
    environment:
      NUXT_DATABASE_URL: ${DATABASE_URL} # currently shared
      NUXT_APP_ENVIRONMENT: development
      NUXT_RETRIEVAL_API_HOST: http://retrieval-api:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  advisor_ui_node_modules:
