group_title: Ingress
workloads:
  - web # most of these pages are layer 7 ingress
  - all
scenarios:
  - all
urls:
  - url: https://learn.microsoft.com/en-us/azure/aks/concepts-network-ingress
    doc_type: overview
    priority: 25
    comments: |
      Good overview with explanation of concepts. Includes tables for comparing application routing addon vs AGC vs service mesh, etc.

  - url: https://learn.microsoft.com/en-us/azure/aks/managed-gateway-api
    doc_type: how-to
    priority: 10
    comments: |
      Focus on description of what Kubernetes Gateway API is, at top of article and AKS's flavor of it.

  # Application Gateway for Containers (AGC)
  - url: https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/overview?toc=/azure/aks/toc.json&bc=/azure/aks/breadcrumb/toc.json
    doc_type: article
    priority: 10
    comments: |
      Overview of AGC from the AGC product page. Remember that AGC is a separate product offering.
  - url: https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/quickstart-deploy-application-gateway-for-containers-alb-controller-addon?toc=%2Fazure%2Faks%2Ftoc.json&bc=%2Fazure%2Faks%2Fbreadcrumb%2Ftoc.json&tabs=azure-cli%2Cazure-cli2
    doc_type: how-to
    priority: 10

  - url: https://learn.microsoft.com/en-us/azure/aks/app-routing
    doc_type: article
    priority: 8
    comments: |
      This article describes a soon to be retired feature. Ingress NGINX project is retired in March 2026. AKS/Microsoft will offer critical security patches only through November 2026. Recommended path is to go Kubernetes Gateway API
